### ISSUE TITLE
予定をカレンダー形式で表示する

### ISSUE THREAD

**Issue by nakamotojp** [ShigeUe/MentorCheckEx#13]
月間メンタリングスケジュールをカレンダー形式で表示できたら良いなって、メンタリング依頼が来るたびに思ってます。

ただ、そんな事思うのは少数派だし、プログラム肥大化の原因になるので流してもらって大丈夫です。

**Comment by ShigeUe** [comment]
暇が出来たので、追加してみました。
ちょっと見にくい＆情報が少ないような気がします。
お気づきの点がありましたら、またissue上げてくださいませ～🙇‍♂️
