### ISSUE TITLE
カリキュラムページをダークモードにしたい

### ISSUE THREAD

**Issue by nakamotojp** [ShigeUe/MentorCheckEx#15]
ダークモード拡張機能を３個利用したが、どれもカリキュラム内容部分に対応してくれなかった。

ディベロッパーツールで見たところ次のところを変更したら良さそうだった。

>背景を黒

[![Image from Gyazo](https://i.gyazo.com/2d6c29a4a2751ec94c9d9d815e3494de.png)](https://gyazo.com/2d6c29a4a2751ec94c9d9d815e3494de)

>文字を白

[![Image from Gyazo](https://i.gyazo.com/2c6fbb736a154511525cc28204802100.png)](https://gyazo.com/2c6fbb736a154511525cc28204802100)

**Comment by ShigeUe** [comment]
カリキュラム部分をダークモード対応にしました。
システムのダークモードに応じて変化するようにしようと思いましたが止めました。
設定画面でチェックをONにしてください。
