### ISSUE TITLE
メンタリング昇順表示

### ISSUE THREAD

**Issue by nakamotojp** [ShigeUe/MentorCheckEx#2]
メンタリングの月間予定表が昇順表示になればいいなって思ったことがあります。

**Comment by ShigeUe** [comment]
どのURLですか？  
「確定メンタリング一覧」ってやつですか？ 2021年8月だと、 `/mentor/schedule/appointments/2021/8` ってURLですね。  
私の方では「日時」で昇順になっていますが、「コースがまたぐとそうならない」とかですかね？

**Comment by nakamotojp** [comment]
実施確定メンタリング
`mentor/appointments`
ですが、メンタリング一覧から見れば昇順だから、無視してください。
すいません。

**Comment by ShigeUe** [comment]
承知しました。

また何かありましたらissueくださいね。
