### ISSUE TITLE
カリキュラムで表示するリスト

### ISSUE THREAD

**Issue by nakamotojp** [ShigeUe/MentorCheckEx#3]
カリキュラムボタンを押した時に表示されるコースを予め自分で選択できるようにしたい。

もしくは、カリキュラムボタンで押した時に表示されるコースを自分の好きな順番で並ばせたい。

理由は、対応コースが多くなると結構な量のリストが表示されるが、日々利用するコースは５コースぐらいだから。

**Comment by ShigeUe** [comment]
v0.2.2で対応しました。
一度カリキュラムを表示してから、プラグインの設定でON／OFFしてみてください！
