### ISSUE TITLE
課題レビュー基準で表示させるリストを限定させる

### ISSUE THREAD

**Issue by nakamotojp** [ShigeUe/MentorCheckEx#4]
課題レビュー基準で表示させるリストを限定したい

理由、複数コース対応していて、結構な量のコースが表示されてしまっているから。

でも、通常業務だと５コースぐらいしか見ない。

**Comment by ShigeUe** [comment]
右上の「業務について」＞「課題レビュー基準」という遷移で表示する画面でよろしいでしょうか？

**Comment by nakamotojp** [comment]
はい、そうです。

**Comment by ShigeUe** [comment]
では、最新バージョンで機能が追加されていると思います。
お試しください。設定の中に一覧があって、チェックボックスでON／OFF出来ます。
こちらの機能で良ければIssueをクローズしますね。

**Comment by nakamotojp** [comment]
設定画面の右上に新しい表示があるのですが、チェックボックスは見当たりませんでした。
別のページでしょうか？
[![Image from Gyazo](https://i.gyazo.com/6cc0516d72a8f3a7e8163fd9f1febae4.png)](https://gyazo.com/6cc0516d72a8f3a7e8163fd9f1febae4)

**Comment by nakamotojp** [comment]
右側に新しい表示がありますがチェックボックスは見当たりませんでした。
別のページでしょうか？
[![Image from Gyazo](https://i.gyazo.com/6a2a8a6ccc1e36fe8019bae6e30a64c2.png)](https://gyazo.com/6a2a8a6ccc1e36fe8019bae6e30a64c2)

**Comment by ShigeUe** [comment]
一度「設定全削除」ボタンを押して、プラグインの設定を削除してください。  
そのまま何も設定せずに、プラグインの設定画面を閉じます。  
　  
その後、課題レビュー一覧のページ、どこかのカリキュラム一覧のページ、受講生の課題レビューの画面、の3画面を見ると、すべてのデータを拾ってきます。  
　  
もう一度プラグインの設定を開いて、必要な設定をしてみてください。

**Comment by nakamotojp** [comment]
おおおおおすごい！

**Comment by nakamotojp** [comment]
設定できました、ありがとうございました！
