### ISSUE TITLE
コメントに飛ぶ機能

### ISSUE THREAD

**Issue by nakamotojp** [ShigeUe/MentorCheckEx#9]
0.2.8 課題レビュー中にコメント入力に飛べるページ内リンクを追加

この機能地味に非常に便利です。

ありがとうございます。

可能であれば、次回更新時で良いのでREADEME.mdに、どの辺に表示される機能か記載があると嬉しいです。

（今READEME.mdに追記していただかなくても大丈夫です、次回別機能の更新の際でお願いします）

[![Image from Gyazo](https://i.gyazo.com/dd018854666e4deb8345aae17cf095a6.png)](https://gyazo.com/dd018854666e4deb8345aae17cf095a6)

**Comment by ShigeUe** [comment]
そちらのリンクは運営側で設置したもので、一番下のコメントに移動します。  
今回 @sasagar さんにPRしていただいたのは、コメント欄に直接移動します。  
`README.md` に追記しました。

ちょっと `README.md` が見づらくなったので、整理整頓しています。  
[こちら](https://github.com/ShigeUe/MentorCheckEx#%E8%AA%B2%E9%A1%8C%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E4%B8%AD%E3%81%AB%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E5%85%A5%E5%8A%9B%E3%81%AB%E9%A3%9B%E3%81%B9%E3%82%8B%E3%83%9A%E3%83%BC%E3%82%B8%E5%86%85%E3%83%AA%E3%83%B3%E3%82%AF%E3%82%92%E8%BF%BD%E5%8A%A0) で見てみてください。
